### ISSUE TITLE
convert all user name/passwords to lowercase

### ISSUE THREAD

**Issue by David5280** [David5280/movie-tracker#13]
We need to convert all user name/passwords to lowercase before posting to the server.

**Comment by vjt960** [comment]
usernames, yes... but passwords too? or emails?

**Comment by David5280** [comment]
Just emails, sorry!

**Comment by vjt960** [comment]
Issue squashed.

**Comment by David5280** [comment]
![](https://media.giphy.com/media/8ZhtXs9wCVGnlfHSb7/giphy.gif)

SQUASHED
